#highlighter: pygments
#markdown: kramdown
#future: true
#kramdown:
#  parse_block_html: true
#  syntax_highlighter: rouge
#markdown: rdiscount
#rdiscount:
#  extensions: [smart]

permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true

# for a normal use at the base of the server change it to "/"
baseurl: /
title: Junjue Wang's Resume
name: Junjue Wang
email: junjuew dot cs dot cmu dot edu
website: junjuewang.net
website_full: https://www.junjuewang.net
github: junjuew
twitter: JunjueWang
google_maps: 'https://goo.gl/maps/K4jX8fPdMA32'
address: 9120 Gates Hillman Center, 4902 Forbes Ave
postcode: 15213
city: Pittsburgh
country: USA
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
