highlighter: pygments
#markdown: kramdown
#future: true
#kramdown:
#  parse_block_html: true
#  syntax_highlighter: rouge
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://biomadeira.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Junjue Wang's Resume
name: Junjue Wang
email: junjuew@cs.cmu.edu
website: junjuewang.net
website_full: https://www.junjuewang.net
github: trending
twitter: twitter
google_maps: 'https://goo.gl/maps/K4jX8fPdMA32'
address: 9120 Gates Hillman Center, 4902 Forbes Ave
postcode: 15213
city: Pittsburgh
country: USA
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
